### PR TITLE
fix: handle values according to their received type, not the column-defined type (fixes #137)

### LINKED ISSUE #137: Bug: NULL is displayed in INTEGER fields when the value is REAL
SQLite is [flexible](https://www.sqlite.org/flextypegood.html) with the data type stored in a field. Even if a column is specified as `INTEGER`, you can still store different types of values, such as `REAL`. In a real scenario, I mistakenly created a table that was supposed to store `REAL` values but configured it as `INTEGER`. This works in practice because SQLite is flexible, and the data can be easily interpreted in a JS environment. However, **LibSQL Studio** displays `NULL`, even though the data is loaded into the pipeline as `float`.

```sql
CREATE TABLE "coordinates" (
    "latitude"      INTEGER NOT NULL,
    "longitude"     INTEGER NOT NULL,
    "address"       TEXT,
    "updatedAt"     INTEGER NOT NULL,
    PRIMARY KEY("latitude","longitude")
) WITHOUT ROWID;

INSERT INTO "main"."coordinates" ("latitude", "longitude", "address", "updatedAt") VALUES ('1.23', '-1.23', '3', '4');
```

image

```
                "type": "execute",
                "result": {
                    "cols": [
                        {
                            "name": "latitude",
                            "decltype": "INTEGER"
                        },
                        {
                            "name": "longitude",
                            "decltype": "INTEGER"
                        },
                        {
                            "name": "address",
                            "decltype": "TEXT"
                        },
                        {
                            "name": "updatedAt",
                            "decltype": "INTEGER"
                        }
                    ],
                    "rows": [
                        [
                            {
                                "type": "float",
                                "value": -23.7128
                            },
                            {
                                "type": "float",
                                "value": -46.5429
                            },
                            {
                                "type": "text",
                                "value": "Av Francisco Prestes Maia 1114 - Santa Terezinha, São Bernardo do Campo - SP, 09770-000, Brazil"
                            },
                            {
                                "type": "integer",
                                "value": "1722964253480"
                            }
                        ],
```

### PR DESCRIPTION
**Pull request by rentalhost**
Since SQLite is flexible with types, we can't blindly trust the column-defined type. Instead, we now determine the display type based on the type of the received data.

**Here's how it works:**

- A `string` received type will be treated as `TEXT`.
- A `bigint` received type will be treated as `INTEGER` (since the `BigNumberCell` component handles `bigint`, which aligns with how `INTEGER` data is managed internally).
- A `number` received type will be treated as `REAL` (because the `NumberCell` component can handle `number`, which can represent both `integer` or `float` in JavaScript, so even if an `INTEGER` is treated as `number`, it won't be an issue).
- An `object` (Array) received type will be treated as `BLOB`.
- `BLOB` or `NULL` types are handled as generic types (managed by the `GenericCell` component).
- When there is no received type (e.g., when inserting a new value), we default to using the column type as before.

**Additional improvements:**

- `useTableResultCellRenderer()` has been refactored into a direct callback instead of a React hook since it no longer has hook dependencies (specifically, `useDatabaseDriver()`). As there was only one use of this hook, I moved the call directly to the final point of use instead of passing it down through component dependencies.

**Additional notes:**

- It would be important to test with other data sources. I only tested with SQLite and Turso.

### CODE REVIEW

**Comment by invisal** [comment]
This approach has several short-coming
- We won't be able to edit cell with NULL value
- We won't be able to edit new inserted cell.
- If header is INTEGER and cell is TEXT. Let say cell value is "LibSQL". Then when user change it to "100" which valid integer, it should handle by BigNumberCell.

I believe you are in the right track, just need a few twist:

```
if (
  header.dataType === TableColumnDataType.INTEGER &&
  databaseDriver.supportBigInt() &&
  isBigNumber(value)
) {
  // BigNumberCell
} else if ((
  header.dataType === TableColumnDataType.INTEGER ||
  header.dataType === TableColumnDataType.REAL
) && isNumber(value)) {
  // NumberCell
} else if (
  header.dataType === TableColumnDataType.TEXT &&
  isString(value)
) {
  // TextCell
} else {
  // GenericCell
}

function isBigNumber(value) {
  if (typeof value === 'bigint') return true;
  if (value === null) return true;
  if (value === undefined) return true;
  
  try {
    BigInt(value);
    return true;
  } catch {
    return false;
  }
}

function isNumber(value) {
  if (typeof value === 'number') return true;
  if (value === null) return true;
  if (value === undefined) return true;
  return Number.isFinite(value);
}

function isString(value) {
  if (typeof value === 'string') return true;
  if (value === null) return true;
  if (value === undefined) return true;
  return false;
}
```

**Comment by rentalhost** [comment]
Regarding the last point, just to be sure I understood correctly: you were making a statement, not asking a question, right? If it’s a question, SQLite will automatically convert a value that looks like a number to an INTEGER when it's received in an INTEGER field, rather than keeping it as the wrong type, TEXT, if that’s the case.

**Comment by invisal** [comment]
> Regarding the last point, just to be sure I understood correctly: you were making a statement, not asking a question, right? If it’s a question, SQLite will automatically convert a value that looks like a number to an INTEGER when it's received in an INTEGER field, rather than keeping it as the wrong type, TEXT, if that’s the case.

I was not sure what was the sqlite behavior, so I was raising concern.

@rentalhost lets me test further. It looks good so far.

**Comment by rentalhost** [comment]
This is specified in the [**Type Affinity**](https://www.sqlite.org/datatype3.html#type_affinity) section, specifically in **section 3.4**.

Note that in the first `INSERT` example, even though all `VALUES` are sent as _strings_, they are converted to their affinity types according to the column type. So, `"500.0"` is kept as a _string_ in a `TEXT` column but is converted to an _integer_ for the `INTEGER` column.

In the third example, the test is done using `500` as an _integer literal_, so it is _cast_ to a _string_ in the `TEXT` column but remains an _integer_ in the `INTEGER` column.

**Pull request merged**
