### PR TITLE
feat: save gh email when login

### LINKED ISSUE #24: Record Github email when login
Add user email address when login via Github in table `user`

### PR DESCRIPTION
**Pull request by thormengkheang**
fix #24

### CODE REVIEW

**Comment by invisal** [comment]
This only work if the user has their email public.
https://stackoverflow.com/questions/35373995/github-user-email-is-null-despite-useremail-scope

You need to make extra request to get the email `https://api.github.com/user/emails`

**Comment by thormengkheang** [comment]
please check again. I check if the email is not available will fetch email from the API

**Comment by rin-yato** [comment]
I think it might be better to group all route handlers into `api/`, otherwise we would be mixing pages and api routes together, this affect both the file structure and also the url.

I suggest this:
- `GET /login/github` -> `GET /api/auth/github`
- `GET /login/github/callback` -> `GET /api/auth/github/callback`

What do you think?

**Comment by rin-yato** [comment]
> I think it might be better to group all route handlers into `api/`, otherwise we would be mixing pages and api routes together, this affect both the file structure and also the url.
> 
> I suggest this:
> 
> * `GET /login/github` -> `GET /api/auth/github`
> * `GET /login/github/callback` -> `GET /api/auth/github/callback`
> 
> What do you think?

Now that I look at it, it's out of scoped for this issue, was bong @invisal the one who added the initial GITHUB auth?

**Review by rin-yato — APPROVED** [review]
Inside scope of the issue, everything looks good to me!

**Review by invisal — APPROVED** [review]
LGTM

**Pull request merged**
